// 새 영상을 추가할 때는 아래 LESSONS 배열에 같은 형식의 객체를 하나 더 넣으세요.
// start와 end는 초 단위입니다. 예: 1분 23.5초 → 83.5
window.LESSONS = [
  {
    id: "morning-routine",
    order: 1,
    title: "La mia routine mattutina",
    topic: "아침 일상 표현",
    level: "A0–A1",
    creator: "Elisa’s Italian School",
    videoTitle: "Slow Italian for Beginners – Morning Routine in Easy Italian",
    videoId: "40ao6UQlx1o",
    sourceUrl: "https://www.youtube.com/watch?v=40ao6UQlx1o",
    durationLabel: "약 3분",
    rangeLabel: "선택 구간 01:00–03:52",
    sentences: [
      { start: 59.8, end: 72.0, it: "La mattina mi alzo dal letto quando la sveglia inizia a suonare.", ko: "아침에는 알람이 울리기 시작하면 침대에서 일어나요." },
      { start: 71.8, end: 80.0, it: "Trin, trin, suona la sveglia, io mi alzo.", ko: "따르릉, 따르릉, 알람이 울리고 저는 일어나요." },
      { start: 79.8, end: 87.0, it: "La mia sveglia suona alle sette di mattina, circa.", ko: "제 알람은 대략 아침 7시에 울려요." },
      { start: 86.8, end: 92.0, it: "Precisamente suona alle sette e cinque.", ko: "정확히는 7시 5분에 울려요." },
      { start: 91.8, end: 96.0, it: "Trin, trin. Suona la sveglia.", ko: "따르릉, 따르릉. 알람이 울려요." },
      { start: 95.8, end: 101.0, it: "Mi alzo e inizio la mia giornata.", ko: "저는 일어나서 하루를 시작해요." },
      { start: 103.8, end: 115.0, it: "Per prima cosa, dopo essermi alzata, dopo che è suonata la sveglia, vado in bagno.", ko: "먼저, 일어나고 알람이 울린 뒤 화장실로 가요." },
      { start: 114.8, end: 127.0, it: "La porta del bagno è chiusa, quindi apro la porta ed entro in bagno.", ko: "화장실 문이 닫혀 있어서 문을 열고 안으로 들어가요." },
      { start: 126.8, end: 135.0, it: "Ma in bagno è buio.", ko: "그런데 화장실 안은 어두워요." },
      { start: 134.8, end: 138.0, it: "È buio, non c’è luce.", ko: "어두워요. 불빛이 없어요." },
      { start: 138.8, end: 144.0, it: "Quindi accendo la luce.", ko: "그래서 불을 켜요." },
      { start: 143.8, end: 147.0, it: "Ecco qui. Ho acceso la luce.", ko: "자, 됐어요. 불을 켰어요." },
      { start: 148.8, end: 152.0, it: "Mi lavo la faccia.", ko: "세수를 해요." },
      { start: 151.8, end: 157.0, it: "Apro il rubinetto. Ho aperto il rubinetto.", ko: "수도꼭지를 열어요. 수도꼭지를 열었어요." },
      { start: 156.8, end: 162.0, it: "E poi mi lavo la faccia.", ko: "그런 다음 세수를 해요." },
      { start: 161.8, end: 171.0, it: "Mi lavo la faccia con l’acqua fredda, di solito abbastanza fredda.", ko: "보통 꽤 차가운 물로 세수를 해요." },
      { start: 170.8, end: 173.0, it: "Ma ora la mia faccia è bagnata.", ko: "그런데 이제 제 얼굴이 젖었어요." },
      { start: 172.8, end: 178.0, it: "Quindi prendo un asciugamano.", ko: "그래서 수건을 하나 집어요." },
      { start: 177.8, end: 187.0, it: "Prendo un asciugamano e mi asciugo la faccia.", ko: "수건을 집어서 얼굴을 닦아요." },
      { start: 186.8, end: 190.0, it: "Ora la mia faccia è asciutta.", ko: "이제 얼굴이 말랐어요." },
      { start: 189.8, end: 198.0, it: "Poi prendo il mio spazzolino, lo spazzolino.", ko: "그다음 제 칫솔을 집어요. 칫솔이에요." },
      { start: 197.8, end: 202.0, it: "E mi lavo i denti.", ko: "그리고 이를 닦아요." },
      { start: 201.8, end: 213.0, it: "Mi lavo i denti, ovviamente non solo con lo spazzolino, ma anche con il dentifricio.", ko: "물론 칫솔만이 아니라 치약도 사용해서 이를 닦아요." },
      { start: 213.8, end: 227.0, it: "Metto il dentifricio sullo spazzolino e poi, con lo spazzolino, mi lavo i denti.", ko: "칫솔에 치약을 묻히고 칫솔로 이를 닦아요." },
      { start: 226.8, end: 232.0, it: "Ok, mi lavo i denti, poi spengo la luce.", ko: "좋아요, 이를 닦고 불을 꺼요." }
    ]
  },
  {
    id: "pizza-preferita",
    order: 2,
    title: "La mia pizza preferita",
    topic: "음식과 가족 이야기",
    level: "A1–A2",
    creator: "Epic Italian Journey",
    videoTitle: "LISTEN & LEARN ITALIAN – Short Story for Complete Beginners (A1-A2)",
    videoId: "ZeYNmb4qHps",
    sourceUrl: "https://www.youtube.com/watch?v=ZeYNmb4qHps",
    durationLabel: "약 2분",
    rangeLabel: "선택 구간 00:28–02:31",
    sentences: [
      { start: 28.0, end: 34.0, it: "Ciao, mi chiamo Luca e oggi voglio raccontarti della mia pizza preferita.", ko: "안녕하세요, 저는 루카이고 오늘 제가 가장 좋아하는 피자에 관해 이야기해 드릴게요." },
      { start: 34.0, end: 44.0, it: "Ogni venerdì sera, la mia famiglia ed io ordiniamo la pizza da una pizzeria vicino a casa nostra.", ko: "매주 금요일 저녁, 우리 가족과 저는 집 근처 피자 가게에서 피자를 주문해요." },
      { start: 44.0, end: 48.0, it: "La pizzeria si chiama Da Mario.", ko: "그 피자 가게의 이름은 ‘다 마리오’예요." },
      { start: 48.0, end: 55.0, it: "Mario, il pizzaiolo, fa le pizze più buone.", ko: "피자 요리사 마리오는 가장 맛있는 피자를 만들어요." },
      { start: 55.0, end: 60.0, it: "Io scelgo sempre la pizza margherita.", ko: "저는 항상 마르게리타 피자를 골라요." },
      { start: 60.0, end: 65.0, it: "La conosci? È una pizza semplice ma molto famosa.", ko: "알고 있나요? 단순하지만 아주 유명한 피자예요." },
      { start: 65.0, end: 73.0, it: "Gli ingredienti sono pomodoro, mozzarella e basilico.", ko: "재료는 토마토, 모차렐라 그리고 바질이에요." },
      { start: 73.0, end: 80.0, it: "Il basilico ha un buon profumo e la mozzarella si scioglie sul pomodoro.", ko: "바질은 향이 좋고 모차렐라는 토마토 위에서 녹아요." },
      { start: 80.0, end: 86.0, it: "Quando la mangio, mi sembra di essere in Italia.", ko: "그 피자를 먹으면 이탈리아에 있는 것처럼 느껴져요." },
      { start: 86.0, end: 91.0, it: "Mia sorella non ama la pizza margherita.", ko: "제 여동생은 마르게리타 피자를 좋아하지 않아요." },
      { start: 91.0, end: 97.0, it: "Lei preferisce la pizza quattro formaggi perché ama il formaggio.", ko: "여동생은 치즈를 좋아해서 콰트로 포르마지 피자를 더 좋아해요." },
      { start: 97.0, end: 103.0, it: "La sua pizza ha mozzarella, gorgonzola, parmigiano e provolone.", ko: "그 피자에는 모차렐라, 고르곤졸라, 파르미자노와 프로볼로네가 들어가요." },
      { start: 103.0, end: 107.0, it: "È molto saporita e cremosa.", ko: "아주 풍미가 좋고 부드러워요." },
      { start: 107.0, end: 116.0, it: "A volte mi dà un pezzetto, ma preferisco sempre la mia margherita.", ko: "가끔 제게 한 조각을 주지만, 저는 언제나 제 마르게리타를 더 좋아해요." },
      { start: 116.0, end: 120.0, it: "A mia mamma piace la pizza vegetariana.", ko: "엄마는 채소 피자를 좋아하세요." },
      { start: 120.0, end: 128.0, it: "Ha molte verdure come zucchine, melanzane, peperoni e pomodori.", ko: "거기에는 주키니, 가지, 피망, 토마토 같은 채소가 많이 들어가요." },
      { start: 128.0, end: 133.0, it: "Dice che è leggera e salutare.", ko: "엄마는 그 피자가 가볍고 건강에 좋다고 말하세요." },
      { start: 133.0, end: 139.0, it: "Dopo aver mangiato la pizza, parliamo e ridiamo.", ko: "피자를 먹은 뒤 우리는 이야기하고 웃어요." },
      { start: 139.0, end: 143.0, it: "A volte guardiamo un film o giochiamo a carte.", ko: "가끔 영화를 보거나 카드놀이를 해요." },
      { start: 143.0, end: 151.0, it: "È una serata speciale con la mia famiglia.", ko: "가족과 함께하는 특별한 저녁이에요." }
    ]
  },
  {
    id: "presentarsi-in-italiano",
    order: 3,
    title: "Presentarsi in italiano",
    topic: "자기소개와 일상 질문",
    level: "A0–A1",
    creator: "Easy Italian",
    videoTitle: "Introduce Yourself in Italian (for absolute beginners) | Super Easy Italian 48",
    videoId: "ieyLUxtwch4",
    sourceUrl: "https://www.youtube.com/watch?v=ieyLUxtwch4",
    durationLabel: "약 1분",
    rangeLabel: "선택 구간 00:35–04:31",
    sentences: [
      { start: 35.6, end: 37.9, it: "Come ti chiami?", ko: "이름이 뭐예요?" },
      { start: 40.6, end: 42.5, it: "Sono Elena, piacere.", ko: "저는 엘레나예요. 반가워요." },
      { start: 44.6, end: 46.3, it: "Mi chiamo Ludovica.", ko: "제 이름은 루도비카예요." },
      { start: 62.6, end: 64.7, it: "Dove abiti?", ko: "어디에 살아요?" },
      { start: 65.5, end: 67.3, it: "Abito a Milano.", ko: "밀라노에 살아요." },
      { start: 73.7, end: 77.4, it: "Di dove sei?", ko: "어디 출신이에요?" },
      { start: 77.5, end: 78.9, it: "Vengo da Venezia.", ko: "베네치아에서 왔어요." },
      { start: 79.9, end: 81.3, it: "Sono inglese.", ko: "저는 영국인이에요." },
      { start: 84.8, end: 85.9, it: "Sono di Roma.", ko: "저는 로마 출신이에요." },
      { start: 94.4, end: 99.9, it: "Io sono nativa di Trento, ma vivo a Milano da tantissimi anni.", ko: "저는 트렌토 태생이지만 아주 오랫동안 밀라노에서 살고 있어요." },
      { start: 206.3, end: 208.3, it: "Che lavoro fai?", ko: "무슨 일을 해요?" },
      { start: 211.7, end: 213.7, it: "Lavoro per una compagnia aerea.", ko: "항공사에서 일해요." },
      { start: 213.6, end: 215.7, it: "Faccio la studentessa.", ko: "저는 학생이에요." },
      { start: 215.6, end: 216.6, it: "Cosa studi?", ko: "무엇을 공부해요?" },
      { start: 216.5, end: 218.8, it: "Studio ingegneria informatica.", ko: "컴퓨터공학을 공부해요." },
      { start: 251.7, end: 254.6, it: "Cosa fai nel tempo libero?", ko: "여가 시간에는 무엇을 해요?" },
      { start: 254.5, end: 258.8, it: "Nel tempo libero pratico sport e mi riposo.", ko: "여가 시간에는 운동을 하고 쉬어요." },
      { start: 260.8, end: 262.9, it: "Mi piace guardare film.", ko: "영화 보는 것을 좋아해요." },
      { start: 264.1, end: 267.1, it: "Mi piace fare le passeggiate.", ko: "산책하는 것을 좋아해요." },
      { start: 267.0, end: 271.4, it: "Mi piace ascoltare la musica e andare in palestra.", ko: "음악을 듣고 헬스장에 가는 것을 좋아해요." }
    ]
  },
  {
    id: "colazione-al-bar",
    order: 4,
    title: "Colazione al bar",
    topic: "카페 주문과 선택 표현",
    level: "A1",
    creator: "Easy Italian",
    videoTitle: "How to Order Breakfast in Italy Like a Local | Easy Italian 261",
    videoId: "Q28_M_fBUT0",
    sourceUrl: "https://www.youtube.com/watch?v=Q28_M_fBUT0",
    durationLabel: "약 1분",
    rangeLabel: "선택 구간 00:52–15:39",
    sentences: [
      { start: 51.8, end: 54.4, it: "Ragazzi, voi vi accomodate?", ko: "여러분, 자리에 앉으실 건가요?" },
      { start: 54.2, end: 56.3, it: "Sì, magari fuori.", ko: "네, 가능하면 밖에요." },
      { start: 55.3, end: 61.2, it: "Allora, prendiamo un cappuccino, un caffè macchiato e un caffè normale.", ko: "그럼 카푸치노 하나, 마키아토 하나, 일반 커피 하나로 할게요." },
      { start: 62.4, end: 64.7, it: "Che brioche vuoi?", ko: "어떤 브리오슈를 원해?" },
      { start: 64.8, end: 68.5, it: "Prendiamo anche una brioche vuota per me.", ko: "저를 위해 속이 없는 브리오슈도 하나 주문할게요." },
      { start: 72.5, end: 74.8, it: "Ecco qua, grazie.", ko: "여기 있습니다. 감사합니다." },
      { start: 420.7, end: 427.5, it: "Buongiorno. Un caffè macchiato decaffeinato, per favore.", ko: "안녕하세요. 디카페인 마키아토 한 잔 부탁드려요." },
      { start: 428.5, end: 432.2, it: "Hai qualcosa di piccolino?", ko: "작은 것으로 뭐가 있나요?" },
      { start: 436.7, end: 439.0, it: "Tu vuoi qualcosa?", ko: "너도 뭐 먹을래?" },
      { start: 439.0, end: 444.4, it: "Una sfogliatella con la cioccolata o la crema. Cosa preferisci?", ko: "초콜릿이나 크림이 든 스폴리아텔라가 있어. 어떤 게 좋아?" },
      { start: 569.4, end: 573.7, it: "Ciao, scusa, posso chiederti com'è questo?", ko: "안녕하세요, 실례지만 이것이 어떤 건지 물어봐도 될까요?" },
      { start: 573.1, end: 579.0, it: "Volevamo una brioche salata con prosciutto cotto e brie.", ko: "익힌 햄과 브리 치즈가 든 짭짤한 브리오슈 하나 주세요." },
      { start: 585.0, end: 591.4, it: "Poi volevamo due spremute d'arancia.", ko: "그리고 생오렌지주스 두 잔 주세요." },
      { start: 591.4, end: 594.0, it: "E tu, Antonella, cosa prendi?", ko: "안토넬라, 너는 무엇을 주문할래?" },
      { start: 593.0, end: 596.4, it: "Un tè e un caffè decaffeinato.", ko: "차 한 잔과 디카페인 커피 한 잔이요." },
      { start: 730.3, end: 732.3, it: "Vuoi assaggiare un po'?", ko: "조금 맛볼래?" },
      { start: 731.9, end: 733.8, it: "No, grazie.", ko: "아니요, 괜찮아요." },
      { start: 783.5, end: 789.3, it: "Buongiorno, per favore, posso avere un cappuccino e una brioche?", ko: "안녕하세요. 카푸치노 한 잔과 브리오슈 하나 주시겠어요?" },
      { start: 847.5, end: 852.5, it: "Avete una bustina di zucchero di canna?", ko: "갈색 설탕 한 봉지가 있나요?" },
      { start: 933.5, end: 939.5, it: "Scusi, ma cosa c'è dentro questa brioche?", ko: "실례합니다. 이 브리오슈 안에는 무엇이 들어 있나요?" }
    ]
  },
  {
    id: "che-programmi-hai",
    order: 5,
    title: "Che programmi hai?",
    topic: "오늘·어제·내일의 계획",
    level: "A1–A2",
    creator: "Easy Italian",
    videoTitle: "Milan, What Are You Doing Today? | Easy Italian 221",
    videoId: "DWsmdW6NVew",
    sourceUrl: "https://www.youtube.com/watch?v=DWsmdW6NVew",
    durationLabel: "약 1분",
    rangeLabel: "선택 구간 00:13–08:41",
    sentences: [
      { start: 12.6, end: 16.1, it: "Che programmi hai per oggi?", ko: "오늘 무슨 계획이 있어요?" },
      { start: 15.6, end: 20.5, it: "Oggi voglio andare alla Rinascente.", ko: "오늘 리나센테에 가고 싶어요." },
      { start: 26.7, end: 32.2, it: "Vado a mangiare da Luini il panzerotto.", ko: "루이니에서 판체로토를 먹으러 가요." },
      { start: 33.8, end: 39.2, it: "E poi vado a fare una passeggiata al Duomo.", ko: "그런 다음 두오모를 산책하러 가요." },
      { start: 42.5, end: 49.6, it: "Mi trovo con i miei cari amici e parenti.", ko: "친한 친구들과 가족들을 만나요." },
      { start: 51.5, end: 55.5, it: "È la prima volta che mangi i panzerotti di Luini?", ko: "루이니의 판체로티를 먹는 건 처음이에요?" },
      { start: 55.0, end: 60.0, it: "No, non è la prima volta. Li mangiavo già da piccola.", ko: "아니요, 처음이 아니에요. 어릴 때부터 먹었어요." },
      { start: 84.7, end: 89.5, it: "Oggi abbiamo fatto colazione in centro.", ko: "오늘 시내에서 아침을 먹었어요." },
      { start: 88.4, end: 93.3, it: "Poi siamo andati a vedere la mostra di Munch.", ko: "그다음 뭉크 전시회를 보러 갔어요." },
      { start: 92.8, end: 99.0, it: "Adesso faremo una passeggiata, un pranzetto e poi un altro giretto in centro.", ko: "이제 산책하고 간단히 점심을 먹은 뒤 시내를 한 바퀴 더 돌 거예요." },
      { start: 98.0, end: 100.6, it: "Com'era la mostra di Munch?", ko: "뭉크 전시는 어땠어요?" },
      { start: 100.4, end: 103.0, it: "Molto bella, la consiglio.", ko: "정말 좋았어요. 추천해요." },
      { start: 106.8, end: 110.2, it: "Siamo andati a fare un po' di shopping.", ko: "쇼핑을 좀 했어요." },
      { start: 109.3, end: 116.3, it: "Adesso andiamo a casa, pranziamo e ci riposiamo un attimo.", ko: "이제 집에 가서 점심을 먹고 잠깐 쉴 거예요." },
      { start: 115.0, end: 118.3, it: "E poi stasera usciamo.", ko: "그리고 오늘 저녁에는 나갈 거예요." },
      { start: 124.8, end: 129.0, it: "Veniamo qua e facciamo l'aperitivo.", ko: "여기에 와서 아페리티보를 해요." },
      { start: 193.5, end: 198.0, it: "E tu, che hai fatto ieri?", ko: "그럼 당신은 어제 무엇을 했어요?" },
      { start: 371.0, end: 380.7, it: "Ieri ho studiato l'inglese perché voglio fare un esame.", ko: "어제는 영어 시험을 보려고 영어 공부를 했어요." },
      { start: 468.7, end: 473.5, it: "Cosa farai domani?", ko: "내일은 무엇을 할 거예요?" },
      { start: 517.0, end: 521.5, it: "Domani mi sveglierò tardi, probabilmente.", ko: "아마 내일은 늦게 일어날 거예요." }
    ]
  },
  {
    id: "serate-in-famiglia",
    order: 6,
    title: "Le serate di una volta",
    topic: "가족·친구와 보내던 시간",
    level: "A1–A2",
    creator: "Italiano Automatico",
    videoTitle: "30 Domande Per Nonna Elide",
    videoId: "t2zmZa3K6hQ",
    sourceUrl: "https://www.youtube.com/watch?v=t2zmZa3K6hQ",
    durationLabel: "약 2분",
    rangeLabel: "선택 구간 16:10–18:10",
    sentences: [
      { start: 970.0, end: 972.0, it: "Di volersi bene.", ko: "서로 아끼는 것이요." },
      { start: 972.0, end: 975.0, it: "Di volersi bene un pochino.", ko: "서로 조금 더 아껴 주는 것이요." },
      { start: 976.0, end: 980.0, it: "Ci riunivamo tutti seduti per terra.", ko: "우리는 모두 바닥에 앉아 모이곤 했어요." },
      { start: 980.0, end: 982.5, it: "Raccontavamo barzellette, giocavamo.", ko: "우스갯소리를 하고 놀곤 했어요." },
      { start: 982.0, end: 985.5, it: "Oggi non si vivono più quelle cose lì.", ko: "요즘은 그런 일을 더 이상 경험하지 않죠." },
      { start: 986.0, end: 988.5, it: "Invece noi eravamo tutti felici.", ko: "하지만 우리는 모두 행복했어요." },
      { start: 988.0, end: 991.5, it: "Tutti seduti assieme, cantavamo, mangiavamo.", ko: "다 같이 앉아서 노래하고 먹었어요." },
      { start: 1004.0, end: 1007.5, it: "Si trovano insieme.", ko: "다 함께 모여요." },
      { start: 1008.0, end: 1012.5, it: "Parlano insieme, pregano insieme, giocano insieme.", ko: "함께 이야기하고, 기도하고, 놀아요." },
      { start: 1037.0, end: 1040.5, it: "Leggere un pochino.", ko: "조금 책을 읽는 것이요." },
      { start: 1040.0, end: 1043.5, it: "Se avevo qualche libro, lo leggevo.", ko: "책이 있으면 읽곤 했어요." },
      { start: 1046.0, end: 1049.5, it: "Noi la sera eravamo sempre in tante.", ko: "우리는 저녁이면 늘 여럿이 함께 있었어요." },
      { start: 1049.0, end: 1054.5, it: "Una canzoncina, un ricordo... Cosa hai mangiato oggi?", ko: "짧은 노래나 추억 이야기, ‘오늘 뭐 먹었어?’ 같은 이야기를 했죠." },
      { start: 1054.0, end: 1058.5, it: "Cantavamo tutte assieme sedute per terra.", ko: "모두 바닥에 앉아 함께 노래했어요." },
      { start: 1059.0, end: 1063.5, it: "Per noi la gioia più bella era riunirci tutte la sera.", ko: "우리에게 가장 큰 기쁨은 저녁에 모두 모이는 것이었어요." },
      { start: 1072.0, end: 1074.5, it: "E d'inverno, come facevate?", ko: "그럼 겨울에는 어떻게 지냈어요?" },
      { start: 1074.0, end: 1078.5, it: "D'inverno giocavamo a tombola.", ko: "겨울에는 톰볼라 놀이를 하곤 했어요." },
      { start: 1078.0, end: 1080.5, it: "Ci riunivamo nelle case.", ko: "집에 모이곤 했어요." },
      { start: 1080.0, end: 1082.5, it: "Giocavate in casa a tombola?", ko: "집에서 톰볼라 놀이를 했어요?" },
      { start: 1084.0, end: 1090.5, it: "Andavamo a casa di una vicina.", ko: "이웃집에 가곤 했어요." }
    ]
  },
  {
    id: "alla-stazione",
    order: 7,
    title: "Alla stazione",
    topic: "기차역과 대중교통",
    level: "A1–A2",
    creator: "Studio Italiano InClasse",
    videoTitle: "Impariamo l'Italiano alla Stazione | Italian Daily Life",
    videoId: "nMW5y7dv5uc",
    sourceUrl: "https://www.youtube.com/watch?v=nMW5y7dv5uc",
    durationLabel: "약 2분",
    rangeLabel: "선택 구간 00:38–12:53",
    sentences: [
      { start: 38.0, end: 44.5, it: "Mi dai tre biglietti dell'autobus, per favore?", ko: "버스표 세 장 주시겠어요?" },
      { start: 64.0, end: 69.5, it: "Siamo alla fermata dell'autobus.", ko: "우리는 버스 정류장에 있어요." },
      { start: 70.0, end: 75.5, it: "Dobbiamo prendere il 61.", ko: "우리는 61번 버스를 타야 해요." },
      { start: 93.0, end: 99.5, it: "Possiamo usare l'obliteratrice digitale.", ko: "디지털 개찰기를 사용할 수 있어요." },
      { start: 99.0, end: 105.5, it: "Si mette il biglietto qui e si convalida il biglietto.", ko: "표를 여기에 넣어서 개찰합니다." },
      { start: 162.0, end: 171.5, it: "Dovete controllare qual è il marciapiede giusto.", ko: "어느 승차 장소가 맞는지 확인해야 해요." },
      { start: 318.0, end: 323.5, it: "Dove vogliamo andare?", ko: "우리 어디로 갈까요?" },
      { start: 323.0, end: 330.5, it: "Posso selezionare il numero di passeggeri.", ko: "승객 수를 선택할 수 있어요." },
      { start: 335.0, end: 343.5, it: "Qui ho gli orari dei treni per Venezia e le varie tariffe.", ko: "여기에 베네치아행 열차 시간과 여러 요금이 나와 있어요." },
      { start: 343.0, end: 347.5, it: "È tutto esaurito.", ko: "전부 매진이에요." },
      { start: 351.0, end: 357.5, it: "Proviamo con un'altra compagnia.", ko: "다른 철도 회사로 시도해 봅시다." },
      { start: 384.0, end: 394.5, it: "Dobbiamo sempre guardare il tabellone degli orari.", ko: "항상 운행 시간 전광판을 확인해야 해요." },
      { start: 394.0, end: 402.5, it: "A sinistra ci sono le partenze e a destra gli arrivi.", ko: "왼쪽에는 출발편, 오른쪽에는 도착편이 있어요." },
      { start: 439.0, end: 447.5, it: "Posso prendere un regionale o un regionale veloce.", ko: "일반 지역 열차나 고속 지역 열차를 탈 수 있어요." },
      { start: 484.0, end: 489.5, it: "Quando sentite questa voce, c'è un annuncio.", ko: "이 목소리가 들리면 안내 방송이 나오는 거예요." },
      { start: 489.0, end: 495.5, it: "In questo periodo c'è purtroppo uno sciopero.", ko: "안타깝게도 지금은 파업 기간이에요." },
      { start: 520.0, end: 524.5, it: "Adesso andiamo ai binari.", ko: "이제 승강장으로 갑시다." },
      { start: 524.0, end: 531.5, it: "Il binario è il posto da dove parte il treno.", ko: "비나리오는 기차가 출발하는 승강장이에요." },
      { start: 548.0, end: 555.5, it: "Potete sempre andare in biglietteria.", ko: "언제든 매표소에 가서 물어볼 수 있어요." },
      { start: 764.0, end: 773.5, it: "Se il biglietto non è convalidato, prendete la multa.", ko: "표를 개찰하지 않으면 벌금을 물어요." }
    ]
  },
  {
    id: "comprare-una-camicia",
    order: 8,
    title: "In un negozio di abbigliamento",
    topic: "옷 고르기·입어 보기·결제하기",
    level: "A1",
    creator: "LinguaMotion Academy",
    videoTitle: "Italian for Clothes Shopping | Useful Phrases & Dialogues",
    videoId: "Di6I80U0EFw",
    sourceUrl: "https://www.youtube.com/watch?v=Di6I80U0EFw",
    durationLabel: "약 1분",
    rangeLabel: "선택 구간 09:04–09:47",
    sentences: [
      { start: 543.9, end: 545.1, it: "Salve!", ko: "안녕하세요!" },
      { start: 545.1, end: 546.3, it: "Posso aiutarla?", ko: "도와드릴까요?" },
      { start: 546.3, end: 549.7, it: "Cerco una camicia.", ko: "셔츠를 찾고 있어요." },
      { start: 549.7, end: 553.7, it: "Vorrei vedere quella camicia bianca lì.", ko: "저기 있는 흰 셔츠를 보고 싶어요." },
      { start: 553.7, end: 554.5, it: "Questa qui?", ko: "이거요?" },
      { start: 554.5, end: 556.7, it: "No, quella bianca un po’ più in là.", ko: "아니요, 조금 더 저쪽에 있는 흰색이요." },
      { start: 556.7, end: 558.2, it: "Ah, ho capito. Questa!", ko: "아, 알겠습니다. 이거요!" },
      { start: 558.2, end: 560.9, it: "Grazie. Bella! Che taglia è?", ko: "고마워요. 예쁘네요! 사이즈가 어떻게 돼요?" },
      { start: 560.9, end: 564.7, it: "Questa è una M.", ko: "이건 M 사이즈예요." },
      { start: 564.7, end: 566.4, it: "Perfetto. Porto la M.", ko: "딱 좋네요. 저는 M 사이즈를 입어요." },
      { start: 566.4, end: 567.4, it: "Posso provarla?", ko: "입어 봐도 될까요?" },
      { start: 567.4, end: 570.9, it: "Ma certo! Il camerino è proprio lì, a destra.", ko: "물론이죠! 탈의실은 바로 저기 오른쪽에 있어요." },
      { start: 570.9, end: 572.6, it: "Grazie.", ko: "고마워요." },
      { start: 572.6, end: 574.9, it: "Mi sta bene.", ko: "저한테 잘 맞아요." },
      { start: 574.9, end: 576.9, it: "Sì, mi piace! La prendo.", ko: "네, 마음에 들어요! 이걸로 살게요." },
      { start: 576.9, end: 578.1, it: "Benissimo!", ko: "아주 좋아요!" },
      { start: 578.1, end: 579.1, it: "Quanto costa?", ko: "얼마예요?" },
      { start: 579.1, end: 581.4, it: "Questa costa trentanove euro.", ko: "이건 39유로예요." },
      { start: 581.4, end: 583.2, it: "Va bene. Pago con la carta.", ko: "좋아요. 카드로 결제할게요." },
      { start: 584.5, end: 587.0, it: "Ecco lo scontrino! Mi raccomando, lo conservi.", ko: "영수증 여기 있습니다! 꼭 보관하세요." }
    ]
  },
  {
    id: "una-giornata-a-scuola",
    order: 9,
    title: "Una giornata alla scuola d’italiano",
    topic: "어학원·교실·친구와의 대화",
    level: "A1–A2",
    creator: "Learn Italian with Lucrezia",
    videoTitle: "Vlog in Italian: una giornata alla scuola d'italiano Dilit",
    videoId: "DC0wb7B1wCE",
    sourceUrl: "https://www.youtube.com/watch?v=DC0wb7B1wCE",
    durationLabel: "약 2분",
    rangeLabel: "선택 구간 00:58–08:15",
    sentences: [
      { start: 58.0, end: 61.2, it: "Ciao Paola, come stai?", ko: "안녕 파올라, 잘 지내?" },
      { start: 61.2, end: 65.1, it: "Tutto bene!", ko: "다 잘 지내!" },
      { start: 65.1, end: 70.1, it: "Per qualsiasi cosa, sono qui al piano terra.", ko: "무슨 일이든 필요하면 저는 1층에 있어요." },
      { start: 70.1, end: 74.6, it: "Ci vediamo dopo per un caffè?", ko: "이따 커피 마시러 만날까요?" },
      { start: 74.6, end: 80.4, it: "Passa una bella giornata con noi.", ko: "우리와 함께 좋은 하루 보내요." },
      { start: 80.4, end: 83.4, it: "Vieni con me, facciamo un giro.", ko: "나랑 같이 가요. 한 바퀴 둘러봅시다." },
      { start: 83.4, end: 89.4, it: "Ci sono tante scale, quindi si rimane in forma.", ko: "계단이 많아서 운동이 돼요." },
      { start: 89.4, end: 93.9, it: "Queste sono le aule.", ko: "여기가 교실들이에요." },
      { start: 93.9, end: 101.6, it: "Molto spaziosa.", ko: "아주 넓네요." },
      { start: 101.6, end: 108.7, it: "Tutte le classi hanno lo schermo oppure le lavagne interattive.", ko: "모든 교실에는 스크린이나 전자칠판이 있어요." },
      { start: 108.8, end: 115.2, it: "Proseguiamo. C’è una meravigliosa terrazza.", ko: "계속 가 볼게요. 멋진 테라스가 있어요." },
      { start: 169.7, end: 174.5, it: "Adesso devo andare in E2, al primo piano.", ko: "이제 2층에 있는 E2 교실로 가야 해요." },
      { start: 177.8, end: 182.5, it: "Buongiorno. Posso?", ko: "안녕하세요. 들어가도 될까요?" },
      { start: 302.4, end: 309.3, it: "Tra qualche minuto c’è una pausa.", ko: "몇 분 뒤에 쉬는 시간이 있어요." },
      { start: 384.1, end: 390.8, it: "Come ti trovi qui?", ko: "여기 생활은 어때요?" },
      { start: 384.1, end: 390.8, it: "Mi piace tantissimo, sono ritornata qui!", ko: "정말 좋아요. 그래서 여기 다시 왔어요!" },
      { start: 426.5, end: 432.6, it: "Facciamo una passeggiata, una visita guidata, un aperitivo.", ko: "산책도 하고, 가이드 투어도 하고, 아페리티보도 해요." },
      { start: 447.7, end: 454.4, it: "Fate lezione all’aperto oggi?", ko: "오늘은 야외에서 수업해요?" },
      { start: 470.1, end: 472.9, it: "Le lezioni sono terminate.", ko: "수업이 끝났어요." },
      { start: 487.5, end: 494.5, it: "Ti ringrazio tanto. Grazie mille a te.", ko: "정말 고마워요. 저야말로 정말 고마워요." }
    ]
  },
  {
    id: "dentro-una-casa-italiana",
    order: 10,
    title: "Dentro una casa italiana",
    topic: "이탈리아 집과 생활 습관",
    level: "A2",
    creator: "Real Italian Conversations",
    videoTitle: "Impara l'italiano in casa: gli oggetti di una casa italiana",
    videoId: "wSEli9nuhR0",
    sourceUrl: "https://www.youtube.com/watch?v=wSEli9nuhR0",
    durationLabel: "약 2분",
    rangeLabel: "선택 구간 04:56–09:33",
    sentences: [
      { start: 296.5, end: 300.8, it: "Un pavimento duro cambia anche il modo di pulire la casa.", ko: "단단한 바닥은 집을 청소하는 방식도 바꿔요." },
      { start: 301.0, end: 304.5, it: "Sulla moquette si passa solo l’aspirapolvere.", ko: "카펫에는 진공청소기만 돌려요." },
      { start: 304.7, end: 309.1, it: "Sulle piastrelle si passa prima la scopa e poi l’acqua.", ko: "타일 바닥은 먼저 빗자루로 쓸고 그다음 물걸레질해요." },
      { start: 309.3, end: 314.5, it: "In ogni casa italiana ci sono un secchio e uno straccio.", ko: "이탈리아 집에는 어디에나 양동이와 대걸레가 있어요." },
      { start: 314.6, end: 319.5, it: "Lo straccio è un panno grande e bagnato, attaccato a un bastone.", ko: "대걸레는 막대에 붙인 크고 젖은 천이에요." },
      { start: 319.6, end: 324.8, it: "Nel secchio si mette acqua calda con un po’ di sapone per pavimenti.", ko: "양동이에는 따뜻한 물과 바닥용 세제를 조금 넣어요." },
      { start: 325.0, end: 329.8, it: "Si lava una stanza per volta e si lascia asciugare il pavimento.", ko: "방을 하나씩 닦고 바닥을 말려요." },
      { start: 330.0, end: 335.9, it: "Dal pavimento duro nasce anche un’altra abitudine: le pantofole.", ko: "단단한 바닥 때문에 생긴 또 다른 습관이 있어요. 바로 실내화예요." },
      { start: 336.0, end: 341.3, it: "Le pantofole sono scarpe morbide che si usano solo dentro casa.", ko: "판토폴레는 집 안에서만 신는 부드러운 실내화예요." },
      { start: 341.4, end: 346.1, it: "D’inverno il marmo e le piastrelle diventano molto freddi.", ko: "겨울에는 대리석과 타일이 아주 차가워져요." },
      { start: 346.3, end: 352.0, it: "Le scarpe di fuori portano acqua e terra su un pavimento appena lavato.", ko: "외출용 신발은 막 닦은 바닥에 물과 흙을 묻혀요." },
      { start: 352.2, end: 356.9, it: "Per questo molte famiglie lasciano le scarpe vicino alla porta.", ko: "그래서 많은 가정이 신발을 문 가까이에 벗어 둬요." },
      { start: 431.1, end: 436.6, it: "Andiamo in bagno, perché lì c’è l’oggetto italiano più famoso di tutti.", ko: "욕실로 가 봅시다. 거기에 가장 유명한 이탈리아 물건이 있거든요." },
      { start: 436.8, end: 441.2, it: "Accanto al water, in quasi ogni bagno, c’è il bidet.", ko: "거의 모든 욕실에는 변기 옆에 비데가 있어요." },
      { start: 441.3, end: 447.9, it: "Il bidet è un oggetto di ceramica basso, con il rubinetto, che serve per lavarsi.", ko: "비데는 씻을 때 쓰는 수도꼭지가 달린 낮은 도기예요." },
      { start: 448.0, end: 452.8, it: "Molti stranieri lo vedono per la prima volta proprio in Italia.", ko: "많은 외국인이 이탈리아에서 비데를 처음 봐요." },
      { start: 538.6, end: 543.9, it: "In moltissime case italiane c’è una cassa di bottiglie d’acqua per terra.", ko: "아주 많은 이탈리아 집에는 생수 한 상자가 바닥에 놓여 있어요." },
      { start: 549.2, end: 555.1, it: "Le famiglie comprano l’acqua al supermercato e la portano a casa ogni settimana.", ko: "가족들은 매주 슈퍼마켓에서 물을 사서 집으로 가져와요." },
      { start: 555.2, end: 561.0, it: "Dal rubinetto esce acqua potabile, cioè acqua che si può bere.", ko: "수도꼭지에서는 마실 수 있는 물, 즉 식수가 나와요." },
      { start: 566.4, end: 573.0, it: "È una questione di fiducia e di gusto.", ko: "그건 신뢰와 취향의 문제예요." }
    ]
  }
];
